"""crear tablas iniciales

Revision ID: 32a622ba856d
Revises: 
Create Date: 2026-01-19 17:00:18.859987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32a622ba856d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_category'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_category_id_category'), 'category', ['id_category'], unique=False)
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('admin', 'operador', name='roleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id_user'), 'users', ['id_user'], unique=False)
    op.create_table('activity',
    sa.Column('id_activity', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('state', sa.Enum('pendiente', 'en_progreso', 'bloqueada', 'completada', 'cancelada', name='activitystateenum'), nullable=False),
    sa.Column('priority', sa.Enum('baja', 'media', 'alta', 'urgente', name='priorityenum'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_category', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id_user'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_category'], ['category.id_category'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_activity')
    )
    op.create_index(op.f('ix_activity_due_date'), 'activity', ['due_date'], unique=False)
    op.create_index(op.f('ix_activity_id_activity'), 'activity', ['id_activity'], unique=False)
    op.create_index(op.f('ix_activity_id_category'), 'activity', ['id_category'], unique=False)
    op.create_index(op.f('ix_activity_id_user'), 'activity', ['id_user'], unique=False)
    op.create_index(op.f('ix_activity_is_active'), 'activity', ['is_active'], unique=False)
    op.create_index(op.f('ix_activity_priority'), 'activity', ['priority'], unique=False)
    op.create_index(op.f('ix_activity_state'), 'activity', ['state'], unique=False)
    op.create_table('historical',
    sa.Column('id_historical', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('modified_field', sa.String(length=50), nullable=True),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_historical')
    )
    op.create_index(op.f('ix_historical_created_at'), 'historical', ['created_at'], unique=False)
    op.create_index(op.f('ix_historical_entity'), 'historical', ['entity'], unique=False)
    op.create_index(op.f('ix_historical_entity_id'), 'historical', ['entity_id'], unique=False)
    op.create_index(op.f('ix_historical_id_historical'), 'historical', ['id_historical'], unique=False)
    op.create_index(op.f('ix_historical_id_user'), 'historical', ['id_user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historical_id_user'), table_name='historical')
    op.drop_index(op.f('ix_historical_id_historical'), table_name='historical')
    op.drop_index(op.f('ix_historical_entity_id'), table_name='historical')
    op.drop_index(op.f('ix_historical_entity'), table_name='historical')
    op.drop_index(op.f('ix_historical_created_at'), table_name='historical')
    op.drop_table('historical')
    op.drop_index(op.f('ix_activity_state'), table_name='activity')
    op.drop_index(op.f('ix_activity_priority'), table_name='activity')
    op.drop_index(op.f('ix_activity_is_active'), table_name='activity')
    op.drop_index(op.f('ix_activity_id_user'), table_name='activity')
    op.drop_index(op.f('ix_activity_id_category'), table_name='activity')
    op.drop_index(op.f('ix_activity_id_activity'), table_name='activity')
    op.drop_index(op.f('ix_activity_due_date'), table_name='activity')
    op.drop_table('activity')
    op.drop_index(op.f('ix_users_id_user'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_category_id_category'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
